# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c785186f4c9fd84131eeee54dfbfa26b1e9b7525a584ef5f48547471ceb46691cf0bd21f796ef20c2a7900e7e67716143655ee6a9002abe5fd5b77b978a2996a

test:
  secret_key_base: ebb4a399a9e045d24c9bdf40760431df4da2dfe8c8bd2cc9054fdfef3f5903948d668565d7dd9bfd00c01f2103dba18caba4d75d1c194d5a42f25100b99bf483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
